Refactor SonarCloud project creation step in Gradle workflow to improve error handling and response messages

diff --git a/.github/workflows/javagradle_build.yml b/.github/workflows/javagradle_build.yml
--- a/.github/workflows/javagradle_build.yml
+++ b/.github/workflows/javagradle_build.yml
@@ -32,30 +32,49 @@ jobs:
       - name: Run Tests
         run: ./gradlew test
   
-      - name: Check and Create SonarCloud Project
-        id: check_create_sonar_project
+      # - name: Check and Create SonarCloud Project
+      #   id: check_create_sonar_project
+      #   run: |
+      #     response=$(curl -s -o /dev/null -w "%{http_code}" \
+      #     -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" \
+      #     "https://sonarcloud.io/api/projects/search?projects=${{ github.event.repository.name }}&organization=migracao-net")
+      #       if [ "$response" -eq 200 ]; then
+      #     echo "exists=true" >> $GITHUB_OUTPUT
+      #     echo "SonarCloud project already exists."
+      #       else
+      #     echo "exists=false" >> $GITHUB_OUTPUT
+      #     echo "SonarCloud project does not exist. Creating..."
+      #     create_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://sonarcloud.io/api/projects/create" \
+      #       -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" \
+      #       -d "organization=migracao-net" \
+      #       -d "project=${{ github.event.repository.name }}" \
+      #       -d "name=${{ github.event.repository.name }}")
+      #     if [ "$create_response" -eq 200 ]; then
+      #       echo "SonarCloud project created successfully."
+      #     else
+      #       echo "Failed to create SonarCloud project. Response code: $create_response"
+      #       exit 1
+      #     fi
+      #       fi
+
+      - name: Create SonarCloud Project (if not exists)
         run: |
           response=$(curl -s -o /dev/null -w "%{http_code}" \
-          -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" \
-          "https://sonarcloud.io/api/projects/search?projects=${{ github.event.repository.name }}&organization=migracao-net")
-            if [ "$response" -eq 200 ]; then
-          echo "exists=true" >> $GITHUB_OUTPUT
-          echo "SonarCloud project already exists."
-            else
-          echo "exists=false" >> $GITHUB_OUTPUT
-          echo "SonarCloud project does not exist. Creating..."
-          create_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://sonarcloud.io/api/projects/create" \
-            -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" \
+            -u "${{ secrets.SONAR_TOKEN }}:" \
+            -X POST "https://sonarcloud.io/api/projects/create" \
             -d "organization=migracao-net" \
             -d "project=${{ github.event.repository.name }}" \
-            -d "name=${{ github.event.repository.name }}")
-          if [ "$create_response" -eq 200 ]; then
-            echo "SonarCloud project created successfully."
+            -d "name=${{ github.event.repository.name }}");
+
+          if [ "$response" = "200" ]; then
+            echo "Projeto criado no SonarCloud."
+          elif [ "$response" = "400" ]; then
+            echo "Projeto já existe no SonarCloud, seguindo..."
           else
-            echo "Failed to create SonarCloud project. Response code: $create_response"
+            echo "Falha ao criar projeto no SonarCloud. Código HTTP: $response"
             exit 1
           fi
-            fi
+        shell: bash
 
       - name: SonarCloud Scan
         uses: SonarSource/sonarqube-scan-action@v5
